exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
encoding: UTF-8

future:      false
lsi:         false
pygments:    true

permalink:   date
markdown:    maruku
excerpt_separator: "\n\n"

author:      netzfisch
name:        harm
email:       tweet@me
twitter:     netzfisch
github:      netzfisch
gravatar_url: http://gravatar.com/avatar/859204385

url:         http://netzfisch.github.io/
title:       "netzfisch's ...wikibrain and blogtaker"
description: "some things that matter to me, mostly tech stuff: linux, ruby, rails ... open source, gagdgets and travel pics"
